title: Gabrielle Catherine Scott
logo: /assets/img/headshot_circle.png
description: Resume and Portfolio of Gabrielle Catherine Scott
url: https://your-username.github.io
author: Gabrielle Catherine Scott
theme: jekyll-theme-minimal
